### ISSUE TITLE
[Question] Moderator adding users

### ISSUE THREAD

**Issue by GieronAdam** [xgerhard/nbqueue#1]
Is there possibility to add / delete user to queue as a moderator (different user) ? 
Let's say im a moderator and i have to remove 3rd user on the list and 5'th user move to first place.

**Comment by xgerhard** [comment]
Hiya! At the moment it is not moment to add users to a queue, only the user itself can join.
As moderator you can delete users, look for the remove command [here](https://github.com/xgerhard/nbqueue/blob/master/README.md).

However what you are suggesting could be a new command/function, boost/promote a user that already is in the queue to the first spot of the queue, I will have a look at that. 
If that's not what you meant let me know.

**Comment by GieronAdam** [comment]
Hey,

yeah ok there is a possibility to remove user as moderator (i dont realise that i should put the remove ID not a username in the command).

Maybe the feature should be just set the position number?
something like: !setposition $user / $user_id 

I have one more question regarding install your app localy, there is any dosc how to set it up locally? and how to test it locally?  i would like to add some commits to your app but i didnt find documentation. :)


Regards,
Adam

**Comment by GieronAdam** [comment]
hi,

if you find some time please provide me information how to setup it locally :).

**Comment by xgerhard** [comment]
Heya, just updated the [readme](https://github.com/xgerhard/nbqueue/blob/master/README.md), please try it out, let me know if you run into any issues.

**Comment by GieronAdam** [comment]
Hi,
that's cool!! thanks :)!

**Comment by Bradleyay** [comment]
Would this be ever possible to do?
