### ISSUE TITLE
Feature request: make max message length configurable

### ISSUE THREAD

**Issue by hangsmateinone** [xgerhard/nbqueue#10]
Hello,
is there a reason why the maximal message length in the !join command is set to 100 characters? It would really help streamers if they could set the maximum themselves, sometimes the queue is used for questions and people can have long questions...

Thank you in advance!

**Comment by xgerhard** [comment]
Hiya! Yes, I can explain why, the max limit of a chat message is 200 characters, so the space is limited for the user message.

This is the current format for the 'next user in the queue' messsage: 
`@$chatUserName next person in queue $queueName is $queueUserName ($queueUserMessage)`

Some user/queue names might be longer, some shorter, so there is little room, I could set it to 130. Don't think making it configurable would be needed.
