### ISSUE TITLE
Default on Queue List: SHow User Messages

### ISSUE THREAD

**Issue by abswan** [xgerhard/nbqueue#11]
Hi--

I really like your NBqueue! For the queue list page, I was curious if there was anyway for the "show user messages" to on. I use the Queue for AMA questions, so it would be nice to make that an option to show the messages when somebody uses the command so I can see their messages. I have an auto-refresher, but as soon as the webpage reloads, it defaults back to messages off.

Cheers

**Comment by xgerhard** [comment]
Thanks for explaining your use case, I just pushed an update, it should now remember if you want to show or hide the messages.
