### ISSUE TITLE
Request | !queue to list the current queue in the twitch chat

### ISSUE THREAD

**Issue by EnderGamingFilms** [xgerhard/nbqueue#3]
So I like that it links to a websit ebut I would prefer if we could just see the queue in chat with a command so we don't have to constantly open up the queue page.

**Comment by xgerhard** [comment]
Thanks for the request, I kinda thought I already had a command for this, but looks like I don't.
I will add a sub-command soon to see the next 5 (?) people in the queue.

**Comment by xgerhard** [comment]
Hiya, I didn't really knew a good commandname to go with this, so for now you can use the command:
`!q who` to show the next 5 people in the queue. If you want to show more: `!q who 10`.

If you want a different command name for it, just add an alias:
`!commands add !commandname -a=!q who $(query)`
