### ISSUE TITLE
[Suggestion] Get a random user when type !next

### ISSUE THREAD

**Issue by Jorseii** [xgerhard/nbqueue#4]
if its possible, when we do !next could we get a random user from the list?

**Comment by xgerhard** [comment]
Hiya, thanks for the suggestion, I added a subcommand called 'random' which can be used just like the 'next' command.

You can use it by typing:
`!q random` to pick one random user or `!q random X` to pick X users.

If you want a separate function for this you can add an alias:
`!commands add !random -a=!q random $(query)`

Now you can use `!random` to pick a random user, or `!random 2` to pick two random users.
