### ISSUE TITLE
Have queue respect following status

### ISSUE THREAD

**Issue by troywoy** [xgerhard/nbqueue#5]
Is there a way, or could you add a way, to make the queue respect whether someone follows or not?

We currently want to do sub games, but many end up being gifted who aren't following so having `-userlevel=follower,subscriber` would be ideal.

**Comment by xgerhard** [comment]
Hiya! This script uses the [userlevel ](https://docs.nightbot.tv/commands/variables/userlevel) provided by Nightbot. This is a single value, and only the highest in the hierarchy will be provided, therefor checking for multiple user levels is currently not possible.

For a workaround, you can always click their name in the chat, to check their following status in you have BTTV.
