### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by chriscolomb** [xgerhard/nbqueue#7]
It seems like the internal server is down... I am also trying to figure out a way to run it locally. The steps in the README are not working for me... Would you be able to help me out?

**Comment by xgerhard** [comment]
Hi there, thanks for the ping, looking into it, server is not happy atm.
What issues are you encountering when you try setting it up locally?

**Comment by xgerhard** [comment]
Alrighty, looks like it's working again. A database connection got locked up.

**Comment by chriscolomb** [comment]
I am unable to do Step 2's "From the nbqueue folder run composer install." Is there anything I am required to install before to set up nbqueue?

**Comment by xgerhard** [comment]
Ah yeah that second step requires composer: https://getcomposer.org/
